### ISSUE TITLE
Dependencies builder is order sensitive

### ISSUE THREAD

**Issue by Rairot** [ebakoba/depper#1]
I am trying to use to this repo but i have encountered a bug or perhaps i am misusing it.

For example, I have 3 dependers named `machine1, machine2 and machine3`  and 2 dependees named `network1, network2`. If i enter the elements in order, dependers before dependees, then it works as expected:
```rust
    let mut dependencies_builder = Dependencies::builder()
        .add_element("machine1".to_string(), vec!["network1".to_string()])
        .add_element("machine2".to_string(), vec!["network1".to_string()])
        .add_element("machine3".to_string(), vec!["network2".to_string()])
        .add_element("network1".to_string(), vec![])
        .add_element("network2".to_string(), vec![]);
```

outputs as expected:
`Tranches: [["network2", "network1"], ["machine1", "machine2", "machine3"]]`

However, if the elements are entered in any other order the results are unpredictable and erroneous. In this example the dependees are inserted before dependers.

```rust
    let mut dependencies_builder = Dependencies::builder()
        .add_element("network1".to_string(), vec![])
        .add_element("network2".to_string(), vec![])
        .add_element("machine1".to_string(), vec!["network1".to_string()])
        .add_element("machine2".to_string(), vec!["network1".to_string()])
        .add_element("machine3".to_string(), vec!["network2".to_string()]);
```

outputs:
`Tranches: [["network2", "network1"], ["network1"], ["machine2", "machine1"]]`

If the first example is how it should be used then i would need to start analyzing each entry and their dependencies myself and i feel like that should be covered by the repo instead

**Comment by ebakoba** [comment]
Thank you for noticing.

Fixed in `0.4.0`
